### ISSUE TITLE
DesktopCamera

### ISSUE THREAD

**Issue by Anonymous-BCFED** [d-mageek/VRC-Mods#3]
## Executive Summary

DesktopCamera fails to modify the Camera menu.

## Environment

* VRChat 1114
* MelonLoader 0.4.3
* DesktopCamera 1.1.4

## Reproduction Steps

1. Install MelonLoader 0.4.3
1. Install DesktopCamera
1. Run VRC

## Expected Outcome
 
When using QuickMenu > Camera, a non-standard menu appears.

## Observed Outcome

No changes to the menu.

**Comment by oestradiol** [comment]
### Hello! Just tested what u presented in the issue. This is what've got:

![image](https://user-images.githubusercontent.com/48662592/127239188-adcfa11b-1d48-479a-8c9f-15f84988a4fb.png)

### I'm currently using the following, and it seems to be working properly:
- VRChat 1114
- MelonLoader 0.4.3
- DesktopCamera 1.1.4

Maybe it's a confusion on how to use the mod? Since I took the command from nitro, I decided to make a change on the menu, making it so that it only shows up when u activate the camera (after all, that's when u can really use it's funcions). To do so, you just need to click the Camera toggle shown on the image above, and the following should happen:

![image](https://user-images.githubusercontent.com/48662592/127239323-9f011428-9d6a-4ac8-834c-e8040efbb39e.png)

**OBS.: In case you're in VR, normally toggling your camera with the original buttons on the bottom should be enough.**

Thank you for the clarity! I didn't manage to get exactly the same issue as you presented, so I'm assuming that's what happened.
I'm closing this issue so, if you're still having the problem, feel free to contact me on discord (my DMs are open, so you should be able to DM me through VRCMG).
UID is [Davi#0003](https://discord.com/users/227477384356429824).
