### ISSUE TITLE
Desktop Camera breaks mirrors

### ISSUE THREAD

**Issue by AmazingGabriel16** [d-mageek/VRC-Mods#5]
Desktop Camera breaks mirrors when you use the VRChive button to take a panorama of the world. The issue carries onto other worlds, a restart appears to be required to solve the issue. I have not yet tested this with the normal panorama which saves the image locally yet.

**Version specifications**
Desktop Camera: 1.1.5
VRChat Unity: 2019.4.31
MelonLoader: 0.4.3 Open-Beta

![VRChat_1920x1080_2021-10-06_08-16-04 534](https://user-images.githubusercontent.com/23047921/136103859-cbece4a5-3b3b-4d4e-b1bf-c1171b49c7fa.png)

**Comment by AmazingGabriel16** [comment]
Update

I have just tested it with the normal panorama which saves locally, the issue is also present there and the mirrors will also break.

**Comment by oestradiol** [comment]
This is not a Desktop Camera glitch. 
Afaik, this is a VRC issue, and has been there for a while.
Before reporting glitches like this, please, make sure to check if the issue is not being caused by other mods, or even VRC itself (which was the case here).
To prove that, u can just take the mod out of the Mods folder and check again, and you'll see the problem will happen again 😉
