### ISSUE TITLE
[BUG] how control Desktop Camera (Wont move Arrow keys or Num pad)

### ISSUE THREAD

**Issue by NekoSuneVR** [d-mageek/VRC-Mods#7]
i tried move camera, and far i seen im able pop out Camera, but unable move it round. last Desktop Camera i have v1.2.1 

since then i didnt seen it got fixed part able activate by button but right now unable move camera round main issue.

if have changed keybinds, it hasnt been updated on readme

**UPDATE**

I just checked Desktop Camera Code, kinda disabled keybinds of it. so Desktop unable move camera anymore but able show it.

**Comment by oestradiol** [comment]
Mhm, that's right. 

Since VRC UI update, both the camera and the UI got completely remade, and thus this mod is almost entirely broken, in such a way that it needs a complete remake.
And so, because of what I said in the readme, I do not plan on updating this mod for now. 
I asked a friend from VRCMG to do it if he wanted to, but since he didn't do in the end, DesktopCamera is just archived here and waiting for someone to update it, pretty much. 

For anyone reading this:
- If you know how to code and want to update this mod, please head to the readme for my contact info;
- If you are just a user, then know that, even though most functions (such as custom menu, movements, etc.) are disabled, as the OP mentioned, _with this mod as it is, you can still use the camera in-game_, since it allows you to activate/deactivate it. Though it's a bit harder without the custom menu, since you'd have to manually click the buttons on the camera itself; To move it around, you can simply use the default VRChat keybinds to move/rotate objects.
